
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action WindowAction;

	private global::Gtk.Action addAction;

	private global::Gtk.Action dndAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action printAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action dndMultipleAction;

	private global::Gtk.Action undoAction;

	private global::Gtk.Action redoAction;

	private global::Gtk.Action cutAction;

	private global::Gtk.Action copyAction;

	private global::Gtk.Action pasteAction;

	private global::Gtk.Action deleteAction;

	private global::Gtk.Action editAction;

	private global::Gtk.Action selectAllAction;

	private global::Gtk.Action SSHAction;

	private global::Gtk.Action FTPAction;

	private global::Gtk.Action RemoteAccessAction;

	private global::Gtk.Action SSHAction1;

	private global::Gtk.Action FTPAction1;

	private global::Gtk.Action RATAction;

	private global::Gtk.Action BuzzerAction;

	private global::Gtk.Action SecurityManagerAction;

	private global::Gtk.Action HeartbreakerAction;

	private global::Gtk.Action KUMPAction;

	private global::Gtk.Action EditorAction;

	private global::Gtk.Action MailManagerAction;

	private global::Gtk.Action NetworkManagerAction;

	private global::Gtk.Action KashmirAction;

	private global::Gtk.Action BinaryEditorAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label3;

	private global::Gtk.HBox hbox1;

	private global::Gtk.DrawingArea drawingarea3;

	private global::Gtk.Label label1;

	private global::Gtk.DrawingArea drawingarea1;

	private global::Gtk.Table table1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button11;

	private global::Gtk.Button button3;

	private global::Gtk.Button button5;

	private global::Gtk.Button button7;

	private global::Gtk.Button button9;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.WindowAction = new global::Gtk.Action("WindowAction", global::Mono.Unix.Catalog.GetString("Window"), null, null);
		this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
		w1.Add(this.WindowAction, null);
		this.addAction = new global::Gtk.Action("addAction", global::Mono.Unix.Catalog.GetString("New Profile"), null, "gtk-add");
		this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New Profile");
		w1.Add(this.addAction, null);
		this.dndAction = new global::Gtk.Action("dndAction", global::Mono.Unix.Catalog.GetString("Open Profile"), null, "gtk-dnd");
		this.dndAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open Profile");
		w1.Add(this.dndAction, null);
		this.saveAction = new global::Gtk.Action("saveAction", global::Mono.Unix.Catalog.GetString("Save Profile"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save Profile");
		w1.Add(this.saveAction, null);
		this.printAction = new global::Gtk.Action("printAction", global::Mono.Unix.Catalog.GetString("Print"), null, "gtk-print");
		this.printAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Print");
		w1.Add(this.printAction, null);
		this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.quitAction, null);
		this.dndMultipleAction = new global::Gtk.Action("dndMultipleAction", global::Mono.Unix.Catalog.GetString("Recent Profiles"), null, "gtk-dnd-multiple");
		this.dndMultipleAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Recent Profiles");
		w1.Add(this.dndMultipleAction, null);
		this.undoAction = new global::Gtk.Action("undoAction", global::Mono.Unix.Catalog.GetString("Undo"), null, "gtk-undo");
		this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Undo");
		w1.Add(this.undoAction, null);
		this.redoAction = new global::Gtk.Action("redoAction", global::Mono.Unix.Catalog.GetString("Redo"), null, "gtk-redo");
		this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Redo");
		w1.Add(this.redoAction, null);
		this.cutAction = new global::Gtk.Action("cutAction", global::Mono.Unix.Catalog.GetString("Cut"), null, "gtk-cut");
		this.cutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cut");
		w1.Add(this.cutAction, null);
		this.copyAction = new global::Gtk.Action("copyAction", global::Mono.Unix.Catalog.GetString("Copy"), null, "gtk-copy");
		this.copyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Copy");
		w1.Add(this.copyAction, null);
		this.pasteAction = new global::Gtk.Action("pasteAction", global::Mono.Unix.Catalog.GetString("Paste"), null, "gtk-paste");
		this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Paste");
		w1.Add(this.pasteAction, null);
		this.deleteAction = new global::Gtk.Action("deleteAction", global::Mono.Unix.Catalog.GetString("Delete"), null, "gtk-delete");
		this.deleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Delete");
		w1.Add(this.deleteAction, null);
		this.editAction = new global::Gtk.Action("editAction", global::Mono.Unix.Catalog.GetString("Rename"), null, "gtk-edit");
		this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Rename");
		w1.Add(this.editAction, null);
		this.selectAllAction = new global::Gtk.Action("selectAllAction", global::Mono.Unix.Catalog.GetString("Select All"), null, "gtk-select-all");
		this.selectAllAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Select All");
		w1.Add(this.selectAllAction, null);
		this.SSHAction = new global::Gtk.Action("SSHAction", global::Mono.Unix.Catalog.GetString("SSH"), null, null);
		this.SSHAction.ShortLabel = global::Mono.Unix.Catalog.GetString("SSH");
		w1.Add(this.SSHAction, null);
		this.FTPAction = new global::Gtk.Action("FTPAction", global::Mono.Unix.Catalog.GetString("FTP"), null, null);
		this.FTPAction.ShortLabel = global::Mono.Unix.Catalog.GetString("FTP");
		w1.Add(this.FTPAction, null);
		this.RemoteAccessAction = new global::Gtk.Action("RemoteAccessAction", global::Mono.Unix.Catalog.GetString("Remote Access"), null, null);
		this.RemoteAccessAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Remote Access");
		w1.Add(this.RemoteAccessAction, null);
		this.SSHAction1 = new global::Gtk.Action("SSHAction1", global::Mono.Unix.Catalog.GetString("SSH"), null, null);
		this.SSHAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("SSH");
		w1.Add(this.SSHAction1, null);
		this.FTPAction1 = new global::Gtk.Action("FTPAction1", global::Mono.Unix.Catalog.GetString("FTP"), null, null);
		this.FTPAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("FTP");
		w1.Add(this.FTPAction1, null);
		this.RATAction = new global::Gtk.Action("RATAction", global::Mono.Unix.Catalog.GetString("RAT"), null, null);
		this.RATAction.ShortLabel = global::Mono.Unix.Catalog.GetString("RAT");
		w1.Add(this.RATAction, null);
		this.BuzzerAction = new global::Gtk.Action("BuzzerAction", global::Mono.Unix.Catalog.GetString("Buzzer"), null, null);
		this.BuzzerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Buzzer");
		w1.Add(this.BuzzerAction, null);
		this.SecurityManagerAction = new global::Gtk.Action("SecurityManagerAction", global::Mono.Unix.Catalog.GetString("Security Manager"), null, null);
		this.SecurityManagerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Security Manager");
		w1.Add(this.SecurityManagerAction, null);
		this.HeartbreakerAction = new global::Gtk.Action("HeartbreakerAction", global::Mono.Unix.Catalog.GetString("Heartbreaker"), null, null);
		this.HeartbreakerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Heartbreaker");
		w1.Add(this.HeartbreakerAction, null);
		this.KUMPAction = new global::Gtk.Action("KUMPAction", global::Mono.Unix.Catalog.GetString("KUMP"), null, null);
		this.KUMPAction.ShortLabel = global::Mono.Unix.Catalog.GetString("KUMP");
		w1.Add(this.KUMPAction, null);
		this.EditorAction = new global::Gtk.Action("EditorAction", global::Mono.Unix.Catalog.GetString("Editor"), null, null);
		this.EditorAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Text Editor");
		w1.Add(this.EditorAction, null);
		this.MailManagerAction = new global::Gtk.Action("MailManagerAction", global::Mono.Unix.Catalog.GetString("Mail Manager"), null, null);
		this.MailManagerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Mail Manager");
		w1.Add(this.MailManagerAction, null);
		this.NetworkManagerAction = new global::Gtk.Action("NetworkManagerAction", global::Mono.Unix.Catalog.GetString("Network Manager"), null, null);
		this.NetworkManagerAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Network Manager");
		w1.Add(this.NetworkManagerAction, null);
		this.KashmirAction = new global::Gtk.Action("KashmirAction", global::Mono.Unix.Catalog.GetString("Kashmir"), null, null);
		this.KashmirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Text Editor");
		w1.Add(this.KashmirAction, null);
		this.BinaryEditorAction = new global::Gtk.Action("BinaryEditorAction", global::Mono.Unix.Catalog.GetString("Binary Editor"), null, null);
		this.BinaryEditorAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Binary Editor");
		w1.Add(this.BinaryEditorAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'><menuite" +
				"m name=\'addAction\' action=\'addAction\'/><menuitem name=\'dndAction\' action=\'dndAct" +
				"ion\'/><menuitem name=\'dndMultipleAction\' action=\'dndMultipleAction\'/><menuitem n" +
				"ame=\'saveAction\' action=\'saveAction\'/><menuitem name=\'printAction\' action=\'print" +
				"Action\'/><menuitem name=\'quitAction\' action=\'quitAction\'/></menu><menu name=\'Edi" +
				"tAction\' action=\'EditAction\'><menuitem name=\'undoAction\' action=\'undoAction\'/><m" +
				"enuitem name=\'redoAction\' action=\'redoAction\'/><menuitem name=\'cutAction\' action" +
				"=\'cutAction\'/><menuitem name=\'copyAction\' action=\'copyAction\'/><menuitem name=\'p" +
				"asteAction\' action=\'pasteAction\'/><menuitem name=\'deleteAction\' action=\'deleteAc" +
				"tion\'/><menuitem name=\'editAction\' action=\'editAction\'/><menuitem name=\'selectAl" +
				"lAction\' action=\'selectAllAction\'/></menu><menu name=\'WindowAction\' action=\'Wind" +
				"owAction\'><menu name=\'RemoteAccessAction\' action=\'RemoteAccessAction\'><menuitem " +
				"name=\'SSHAction1\' action=\'SSHAction1\'/><menuitem name=\'FTPAction1\' action=\'FTPAc" +
				"tion1\'/><menuitem name=\'RATAction\' action=\'RATAction\'/><menuitem name=\'BuzzerAct" +
				"ion\' action=\'BuzzerAction\'/></menu><menu name=\'SecurityManagerAction\' action=\'Se" +
				"curityManagerAction\'><menuitem name=\'HeartbreakerAction\' action=\'HeartbreakerAct" +
				"ion\'/><menuitem name=\'KUMPAction\' action=\'KUMPAction\'/></menu><menu name=\'Editor" +
				"Action\' action=\'EditorAction\'><menuitem name=\'KashmirAction\' action=\'KashmirActi" +
				"on\'/><menuitem name=\'BinaryEditorAction\' action=\'BinaryEditorAction\'/></menu><me" +
				"nuitem name=\'MailManagerAction\' action=\'MailManagerAction\'/><menuitem name=\'Netw" +
				"orkManagerAction\' action=\'NetworkManagerAction\'/></menu><menu/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Welcome to GazLAxe");
		this.vbox2.Add(this.label3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
		w3.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea3 = new global::Gtk.DrawingArea();
		this.drawingarea3.Name = "drawingarea3";
		this.hbox1.Add(this.drawingarea3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.drawingarea3]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.WidthRequest = 270;
		this.label1.HeightRequest = 130;
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("GazLAxe is the world\'s first open-source GUI Hacking tool. It has the following f" +
				"eatures and more:");
		this.label1.Wrap = true;
		this.label1.Justify = ((global::Gtk.Justification)(3));
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w5.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea();
		this.drawingarea1.Name = "drawingarea1";
		this.hbox1.Add(this.drawingarea1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.drawingarea1]));
		w6.Position = 2;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w7.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Remote Access");
		this.table1.Add(this.button1);
		// Container child table1.Gtk.Table+TableChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("Swarm Controller");
		this.table1.Add(this.button11);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.button11]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Password Guesser");
		this.table1.Add(this.button3);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.button3]));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Text Editor");
		this.table1.Add(this.button5);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.button5]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Mail Manager");
		this.table1.Add(this.button7);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.button7]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("Network Manager");
		this.table1.Add(this.button9);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.button9]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		this.vbox2.Add(this.table1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
		w14.Position = 2;
		w14.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 486;
		this.DefaultHeight = 308;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SSHAction1.Activated += new global::System.EventHandler(this.openSSH);
		this.FTPAction1.Activated += new global::System.EventHandler(this.openFTP);
		this.RATAction.Activated += new global::System.EventHandler(this.openRAT);
		this.BuzzerAction.Activated += new global::System.EventHandler(this.openBuzzer);
		this.HeartbreakerAction.Activated += new global::System.EventHandler(this.openHeartbreaker);
		this.KUMPAction.Activated += new global::System.EventHandler(this.openKUMP);
		this.button5.Clicked += new global::System.EventHandler(this.openKasmir);
		this.button3.Clicked += new global::System.EventHandler(this.openHeartbreaker);
		this.button11.Clicked += new global::System.EventHandler(this.openBuzzer);
		this.button1.Clicked += new global::System.EventHandler(this.openSSH);
	}
}
