
// This file has been generated by the GUI designer. Do not modify.
namespace ryuk
{
	public partial class HeartbreakerLogin
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action WindowAction;

		private global::Gtk.VBox vbox4;

		private global::Gtk.MenuBar menubar5;

		private global::Gtk.Table table7;

		private global::Gtk.Button button6;

		private global::Gtk.Button button7;

		private global::Gtk.Button button8;

		private global::Gtk.Label label13;

		private global::Gtk.Label label15;

		private global::Gtk.Label label17;

		private global::Gtk.Expander expander1;

		private global::Gtk.Table table8;

		private global::Gtk.CheckButton checkbutton1;

		private global::Gtk.CheckButton checkbutton3;

		private global::Gtk.CheckButton checkbutton4;

		private global::Gtk.CheckButton checkbutton6;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.Label label19;

		private global::Gtk.Label label25;

		private global::Gtk.Label GtkLabel10;

		private global::Gtk.Button button4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ryuk.HeartbreakerLogin
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.WindowAction = new global::Gtk.Action("WindowAction", global::Mono.Unix.Catalog.GetString("Window"), null, null);
			this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
			w1.Add(this.WindowAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ryuk.HeartbreakerLogin";
			this.Title = global::Mono.Unix.Catalog.GetString("HeartbreakerLogin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ryuk.HeartbreakerLogin.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar5\'><menu name=\'FileAction\' action=\'FileAction\'/><menu n" +
					"ame=\'EditAction\' action=\'EditAction\'/><menu name=\'WindowAction\' action=\'WindowAc" +
					"tion\'/></menubar></ui>");
			this.menubar5 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar5")));
			this.menubar5.Name = "menubar5";
			this.vbox4.Add(this.menubar5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.menubar5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table7 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.button6 = new global::Gtk.Button();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Choose File");
			this.table7.Add(this.button6);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table7[this.button6]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			// Container child table7.Gtk.Table+TableChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Choose File");
			this.table7.Add(this.button7);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table7[this.button7]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			// Container child table7.Gtk.Table+TableChild
			this.button8 = new global::Gtk.Button();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString("Choose File");
			this.table7.Add(this.button8);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table7[this.button8]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child table7.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Possible Domains File:");
			this.table7.Add(this.label13);
			// Container child table7.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Possible Usernames File:");
			this.table7.Add(this.label15);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table7[this.label15]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			// Container child table7.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Possible Passwords File:");
			this.table7.Add(this.label17);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table7[this.label17]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			this.vbox4.Add(this.table7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.table7]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander(null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.table8 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.table8.Name = "table8";
			this.table8.RowSpacing = ((uint)(6));
			this.table8.ColumnSpacing = ((uint)(6));
			// Container child table8.Gtk.Table+TableChild
			this.checkbutton1 = new global::Gtk.CheckButton();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("Generate Additional Special Characters");
			this.checkbutton1.Active = true;
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.table8.Add(this.checkbutton1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table8[this.checkbutton1]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			// Container child table8.Gtk.Table+TableChild
			this.checkbutton3 = new global::Gtk.CheckButton();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString("Split Possible Passwords");
			this.checkbutton3.Active = true;
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.table8.Add(this.checkbutton3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table8[this.checkbutton3]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			// Container child table8.Gtk.Table+TableChild
			this.checkbutton4 = new global::Gtk.CheckButton();
			this.checkbutton4.CanFocus = true;
			this.checkbutton4.Name = "checkbutton4";
			this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString("Generate Additional Numbers");
			this.checkbutton4.Active = true;
			this.checkbutton4.DrawIndicator = true;
			this.checkbutton4.UseUnderline = true;
			this.table8.Add(this.checkbutton4);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table8[this.checkbutton4]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			// Container child table8.Gtk.Table+TableChild
			this.checkbutton6 = new global::Gtk.CheckButton();
			this.checkbutton6.CanFocus = true;
			this.checkbutton6.Name = "checkbutton6";
			this.checkbutton6.Label = global::Mono.Unix.Catalog.GetString("Generate Additional Letters");
			this.checkbutton6.Active = true;
			this.checkbutton6.DrawIndicator = true;
			this.checkbutton6.UseUnderline = true;
			this.table8.Add(this.checkbutton6);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table8[this.checkbutton6]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			// Container child table8.Gtk.Table+TableChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("CSV (First Column)"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("CSV (Second Column)"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("CSV (Third Column)"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("New-Line"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("JSON"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 0;
			this.table8.Add(this.combobox1);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table8[this.combobox1]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			// Container child table8.Gtk.Table+TableChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("Jack the Ripper"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("Levee Breaker"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("Seven Nation Army"));
			this.combobox3.Name = "combobox3";
			this.combobox3.Active = 1;
			this.table8.Add(this.combobox3);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table8[this.combobox3]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			// Container child table8.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("File Format");
			this.table8.Add(this.label19);
			// Container child table8.Gtk.Table+TableChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Algorithm");
			this.table8.Add(this.label25);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table8[this.label25]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			this.expander1.Add(this.table8);
			this.GtkLabel10 = new global::Gtk.Label();
			this.GtkLabel10.Name = "GtkLabel10";
			this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString("Extra Heartbreaker Options");
			this.GtkLabel10.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel10;
			this.vbox4.Add(this.expander1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.expander1]));
			w19.Position = 2;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Start Heartbreaker");
			this.vbox4.Add(this.button4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button4]));
			w20.Position = 3;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 571;
			this.DefaultHeight = 480;
			this.Show();
			this.button8.Clicked += new global::System.EventHandler(this.passwordsFileChanged);
			this.button7.Clicked += new global::System.EventHandler(this.usernamesFileChanged);
			this.button6.Clicked += new global::System.EventHandler(this.domainFileChanged);
			this.combobox3.Changed += new global::System.EventHandler(this.algorithmChanged);
			this.combobox1.Changed += new global::System.EventHandler(this.fileFormatChanged);
			this.checkbutton6.Toggled += new global::System.EventHandler(this.boolLettersChanged);
			this.checkbutton4.Toggled += new global::System.EventHandler(this.boolNumsChanged);
			this.checkbutton3.Toggled += new global::System.EventHandler(this.boolSplitChanged);
			this.checkbutton1.Toggled += new global::System.EventHandler(this.boolSpecialChanged);
			this.button4.Clicked += new global::System.EventHandler(this.startHeartbreaker);
		}
	}
}
