
// This file has been generated by the GUI designer. Do not modify.
namespace ryuk
{
	public partial class RemoteLogin
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action WindowAction;

		private global::Gtk.VBox vbox3;

		private global::Gtk.MenuBar menubar3;

		private global::Gtk.Table table3;

		private global::Gtk.ComboBoxEntry comboboxentry5;

		private global::Gtk.ComboBoxEntry comboboxentry7;

		private global::Gtk.Entry entry3;

		private global::Gtk.Label label11;

		private global::Gtk.Label label7;

		private global::Gtk.Label label9;

		private global::Gtk.Expander expander3;

		private global::Gtk.Table table5;

		private global::Gtk.CheckButton checkbutton6;

		private global::Gtk.Entry entry11;

		private global::Gtk.Entry entry9;

		private global::Gtk.Label label17;

		private global::Gtk.Label label19;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Button button3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ryuk.RemoteLogin
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.WindowAction = new global::Gtk.Action("WindowAction", global::Mono.Unix.Catalog.GetString("Window"), null, null);
			this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
			w1.Add(this.WindowAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ryuk.RemoteLogin";
			this.Title = global::Mono.Unix.Catalog.GetString("RemoteLogin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ryuk.RemoteLogin.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar3\'><menu name=\'FileAction\' action=\'FileAction\'/><menu n" +
					"ame=\'EditAction\' action=\'EditAction\'/><menu name=\'WindowAction\' action=\'WindowAc" +
					"tion\'/></menubar></ui>");
			this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
			this.menubar3.Name = "menubar3";
			this.vbox3.Add(this.menubar3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.comboboxentry5 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry5.Name = "comboboxentry5";
			this.table3.Add(this.comboboxentry5);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.comboboxentry5]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table3.Gtk.Table+TableChild
			this.comboboxentry7 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry7.Name = "comboboxentry7";
			this.table3.Add(this.comboboxentry7);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.comboboxentry7]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table3.Gtk.Table+TableChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.table3.Add(this.entry3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.entry3]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Domain");
			this.table3.Add(this.label11);
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Username");
			this.table3.Add(this.label7);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Password");
			this.table3.Add(this.label9);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.label9]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			this.vbox3.Add(this.table3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table3]));
			w9.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander3 = new global::Gtk.Expander(null);
			this.expander3.CanFocus = true;
			this.expander3.Name = "expander3";
			this.expander3.Expanded = true;
			// Container child expander3.Gtk.Container+ContainerChild
			this.table5 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.checkbutton6 = new global::Gtk.CheckButton();
			this.checkbutton6.CanFocus = true;
			this.checkbutton6.Name = "checkbutton6";
			this.checkbutton6.Label = global::Mono.Unix.Catalog.GetString("Use Key Encryption");
			this.checkbutton6.DrawIndicator = true;
			this.checkbutton6.UseUnderline = true;
			this.table5.Add(this.checkbutton6);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5[this.checkbutton6]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry11 = new global::Gtk.Entry();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '●';
			this.table5.Add(this.entry11);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table5[this.entry11]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '●';
			this.table5.Add(this.entry9);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table5[this.entry9]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Private Key");
			this.table5.Add(this.label17);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table5[this.label17]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Passphrase");
			this.table5.Add(this.label19);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table5[this.label19]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.expander3.Add(this.table5);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("Extra Options");
			this.GtkLabel4.UseUnderline = true;
			this.expander3.LabelWidget = this.GtkLabel4;
			this.vbox3.Add(this.expander3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.expander3]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Start Whatever");
			this.vbox3.Add(this.button3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button3]));
			w17.Position = 3;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 375;
			this.DefaultHeight = 283;
			this.Show();
			this.entry3.Changed += new global::System.EventHandler(this.PasswordChanged);
			this.comboboxentry7.Changed += new global::System.EventHandler(this.UsernameChanged);
			this.comboboxentry5.Changed += new global::System.EventHandler(this.DomainChanged);
			this.button3.Clicked += new global::System.EventHandler(this.StartClicked);
		}
	}
}
