
// This file has been generated by the GUI designer. Do not modify.
namespace ryuk
{
	public partial class KUMPResponse
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action ExportAction;

		private global::Gtk.Action PrintAction;

		private global::Gtk.Action CopyPublicKeyAction;

		private global::Gtk.Action CopyPrivateKeyAction;

		private global::Gtk.Action SaveAsJSONFileAction;

		private global::Gtk.Action SaveAsCSVFileAction;

		private global::Gtk.Action SaveAsTextFileAction;

		private global::Gtk.Action NewEmailWithKeysAction;

		private global::Gtk.Action WindowAction;

		private global::Gtk.Action SafeCloseAction;

		private global::Gtk.VBox vbox3;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.Table table3;

		private global::Gtk.Button button5;

		private global::Gtk.Button button7;

		private global::Gtk.Button button9;

		private global::Gtk.ComboBox combobox2;

		private global::Gtk.Label label5;

		private global::Gtk.Label label7;

		private global::Gtk.Expander expander1;

		private global::Gtk.Table table4;

		private global::Gtk.CheckButton checkbutton1;

		private global::Gtk.CheckButton checkbutton3;

		private global::Gtk.CheckButton checkbutton5;

		private global::Gtk.ComboBox combobox4;

		private global::Gtk.Entry entry5;

		private global::Gtk.Entry entry7;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Label label11;

		private global::Gtk.Label label15;

		private global::Gtk.Label label9;

		private global::Gtk.Label GtkLabel10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ryuk.KUMPResponse
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.ExportAction = new global::Gtk.Action("ExportAction", global::Mono.Unix.Catalog.GetString("Export"), null, null);
			this.ExportAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Export");
			w1.Add(this.ExportAction, null);
			this.PrintAction = new global::Gtk.Action("PrintAction", global::Mono.Unix.Catalog.GetString("Print"), null, null);
			this.PrintAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Print");
			w1.Add(this.PrintAction, null);
			this.CopyPublicKeyAction = new global::Gtk.Action("CopyPublicKeyAction", global::Mono.Unix.Catalog.GetString("Copy Public Key"), null, null);
			this.CopyPublicKeyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Copy Public Key");
			w1.Add(this.CopyPublicKeyAction, null);
			this.CopyPrivateKeyAction = new global::Gtk.Action("CopyPrivateKeyAction", global::Mono.Unix.Catalog.GetString("Copy Private Key"), null, null);
			this.CopyPrivateKeyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Copy Private Key");
			w1.Add(this.CopyPrivateKeyAction, null);
			this.SaveAsJSONFileAction = new global::Gtk.Action("SaveAsJSONFileAction", global::Mono.Unix.Catalog.GetString("Save as JSON File"), null, null);
			this.SaveAsJSONFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as JSON File");
			w1.Add(this.SaveAsJSONFileAction, null);
			this.SaveAsCSVFileAction = new global::Gtk.Action("SaveAsCSVFileAction", global::Mono.Unix.Catalog.GetString("Save as CSV File"), null, null);
			this.SaveAsCSVFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as CSV File");
			w1.Add(this.SaveAsCSVFileAction, null);
			this.SaveAsTextFileAction = new global::Gtk.Action("SaveAsTextFileAction", global::Mono.Unix.Catalog.GetString("Save as Text File"), null, null);
			this.SaveAsTextFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as Text File");
			w1.Add(this.SaveAsTextFileAction, null);
			this.NewEmailWithKeysAction = new global::Gtk.Action("NewEmailWithKeysAction", global::Mono.Unix.Catalog.GetString("New Email with Keys"), null, null);
			this.NewEmailWithKeysAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New Email with Keys");
			w1.Add(this.NewEmailWithKeysAction, null);
			this.WindowAction = new global::Gtk.Action("WindowAction", global::Mono.Unix.Catalog.GetString("Window"), null, null);
			this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
			w1.Add(this.WindowAction, null);
			this.SafeCloseAction = new global::Gtk.Action("SafeCloseAction", global::Mono.Unix.Catalog.GetString("Safe Close"), null, null);
			this.SafeCloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Safe Close");
			w1.Add(this.SafeCloseAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ryuk.KUMPResponse";
			this.Title = global::Mono.Unix.Catalog.GetString("KUMPResponse");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ryuk.KUMPResponse.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'/><menu name='WindowAction' action='WindowAction'><menuitem name='SafeCloseAction' action='SafeCloseAction'/></menu><menu name='ExportAction' action='ExportAction'><menuitem name='PrintAction' action='PrintAction'/><separator/><menuitem name='CopyPublicKeyAction' action='CopyPublicKeyAction'/><menuitem name='CopyPrivateKeyAction' action='CopyPrivateKeyAction'/><separator/><menuitem name='SaveAsJSONFileAction' action='SaveAsJSONFileAction'/><menuitem name='SaveAsCSVFileAction' action='SaveAsCSVFileAction'/><menuitem name='SaveAsTextFileAction' action='SaveAsTextFileAction'/><separator/><menuitem name='NewEmailWithKeysAction' action='NewEmailWithKeysAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox3.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Run");
			this.table3.Add(this.button5);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.button5]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.table3.Add(this.button7);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.button7]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Select File");
			this.table3.Add(this.button9);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.button9]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.combobox2 = global::Gtk.ComboBox.NewText();
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("Change Password"));
			this.combobox2.AppendText(global::Mono.Unix.Catalog.GetString("New User"));
			this.combobox2.Name = "combobox2";
			this.combobox2.Active = 0;
			this.table3.Add(this.combobox2);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.combobox2]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			// Container child table3.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Method");
			this.table3.Add(this.label5);
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Footprint");
			this.table3.Add(this.label7);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			this.vbox3.Add(this.table3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.table3]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander(null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			this.expander1.Expanded = true;
			// Container child expander1.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.checkbutton1 = new global::Gtk.CheckButton();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("Use Footprint");
			this.checkbutton1.Active = true;
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.table4.Add(this.checkbutton1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4[this.checkbutton1]));
			w10.YOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table4.Gtk.Table+TableChild
			this.checkbutton3 = new global::Gtk.CheckButton();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString("Use Custom Password and Username");
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.table4.Add(this.checkbutton3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4[this.checkbutton3]));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			// Container child table4.Gtk.Table+TableChild
			this.checkbutton5 = new global::Gtk.CheckButton();
			this.checkbutton5.CanFocus = true;
			this.checkbutton5.Name = "checkbutton5";
			this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString("Purge Terminal History");
			this.checkbutton5.DrawIndicator = true;
			this.checkbutton5.UseUnderline = true;
			this.table4.Add(this.checkbutton5);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4[this.checkbutton5]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.combobox4 = global::Gtk.ComboBox.NewText();
			this.combobox4.AppendText(global::Mono.Unix.Catalog.GetString("Windows"));
			this.combobox4.AppendText(global::Mono.Unix.Catalog.GetString("Mac"));
			this.combobox4.AppendText(global::Mono.Unix.Catalog.GetString("Linux"));
			this.combobox4.Name = "combobox4";
			this.combobox4.Active = 0;
			this.table4.Add(this.combobox4);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4[this.combobox4]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			// Container child table4.Gtk.Table+TableChild
			this.entry5 = new global::Gtk.Entry();
			this.entry5.Sensitive = false;
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '●';
			this.table4.Add(this.entry5);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4[this.entry5]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			// Container child table4.Gtk.Table+TableChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.Sensitive = false;
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '●';
			this.table4.Add(this.entry7);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4[this.entry7]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			// Container child table4.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.table4.Add(this.hseparator1);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4[this.hseparator1]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.table4.Add(this.hseparator3);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4[this.hseparator3]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Sensitive = false;
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("New Password");
			this.table4.Add(this.label11);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table4[this.label11]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			// Container child table4.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Remote System Type");
			this.table4.Add(this.label15);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table4[this.label15]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Sensitive = false;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("New Username");
			this.table4.Add(this.label9);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table4[this.label9]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			this.expander1.Add(this.table4);
			this.GtkLabel10 = new global::Gtk.Label();
			this.GtkLabel10.Name = "GtkLabel10";
			this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString("Extra Options");
			this.GtkLabel10.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel10;
			this.vbox3.Add(this.expander1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.expander1]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 2;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 545;
			this.DefaultHeight = 335;
			this.Show();
			this.button9.Clicked += new global::System.EventHandler(this.selectFootprint);
			this.button5.Clicked += new global::System.EventHandler(this.runMethod);
			this.checkbutton3.Toggled += new global::System.EventHandler(this.usernameToggled);
			this.checkbutton1.Toggled += new global::System.EventHandler(this.footprintToggled);
		}
	}
}
