
// This file has been generated by the GUI designer. Do not modify.
namespace ryuk
{
	public partial class SSHTerminal
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action WindowAction;

		private global::Gtk.Action SafeCloseAction;

		private global::Gtk.Action SessionAction;

		private global::Gtk.VBox vbox4;

		private global::Gtk.MenuBar menubar3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Entry entry5;

		private global::Gtk.Button button19;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ryuk.SSHTerminal
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.WindowAction = new global::Gtk.Action("WindowAction", global::Mono.Unix.Catalog.GetString("Window"), null, null);
			this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
			w1.Add(this.WindowAction, null);
			this.SafeCloseAction = new global::Gtk.Action("SafeCloseAction", global::Mono.Unix.Catalog.GetString("Safe Close"), null, null);
			this.SafeCloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Safe Close");
			w1.Add(this.SafeCloseAction, null);
			this.SessionAction = new global::Gtk.Action("SessionAction", global::Mono.Unix.Catalog.GetString("Session"), null, null);
			this.SessionAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Session");
			w1.Add(this.SessionAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ryuk.SSHTerminal";
			this.Title = global::Mono.Unix.Catalog.GetString("SSHTerminal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ryuk.SSHTerminal.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar3'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'/><menu name='WindowAction' action='WindowAction'/><menu name='SessionAction' action='SessionAction'><menuitem name='SafeCloseAction' action='SafeCloseAction'/></menu></menubar></ui>");
			this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
			this.menubar3.Name = "menubar3";
			this.vbox4.Add(this.menubar3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.menubar3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.GtkScrolledWindow.Add(this.textview1);
			this.vbox4.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry5 = new global::Gtk.Entry();
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '●';
			this.hbox7.Add(this.entry5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry5]));
			w5.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button19 = new global::Gtk.Button();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseUnderline = true;
			this.button19.Label = global::Mono.Unix.Catalog.GetString("Enter Command");
			this.hbox7.Add(this.button19);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button19]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add(this.hbox7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 691;
			this.DefaultHeight = 434;
			this.Show();
			this.SafeCloseAction.Activated += new global::System.EventHandler(this.safeClose);
			this.textview1.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.ScrollToEnd);
			this.entry5.EditingDone += new global::System.EventHandler(this.commandTextEntered);
			this.button19.Clicked += new global::System.EventHandler(this.commandEntered);
		}
	}
}
