
// This file has been generated by the GUI designer. Do not modify.
namespace ryuk
{
	public partial class FilePicker
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.FileChooserWidget filechooserwidget4;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button button11;

		private global::Gtk.Button button9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ryuk.FilePicker
			this.Name = "ryuk.FilePicker";
			this.Title = global::Mono.Unix.Catalog.GetString("FilePicker");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ryuk.FilePicker.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.filechooserwidget4 = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(0)));
			this.filechooserwidget4.Name = "filechooserwidget4";
			this.vbox5.Add(this.filechooserwidget4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.filechooserwidget4]));
			w1.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button();
			this.button11.CanFocus = true;
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			this.hbox2.Add(this.button11);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button11]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString("Choose");
			this.hbox2.Add(this.button9);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button9]));
			w3.Position = 1;
			this.vbox5.Add(this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 482;
			this.DefaultHeight = 366;
			this.Show();
			this.filechooserwidget4.UpdatePreview += new global::System.EventHandler(this.filePicked);
			this.button11.Clicked += new global::System.EventHandler(this.cancelSelection);
			this.button9.Clicked += new global::System.EventHandler(this.chooseFile);
		}
	}
}
