
// This file has been generated by the GUI designer. Do not modify.
namespace ryuk
{
	public partial class KashmirEditor
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action WindowAction;

		private global::Gtk.Action EncryptionAction;

		private global::Gtk.Action CesarAction;

		private global::Gtk.Action DecryptAction;

		private global::Gtk.Action CesarAction1;

		private global::Gtk.Action MD5Action;

		private global::Gtk.Action MD5Action1;

		private global::Gtk.VBox vbox6;

		private global::Gtk.MenuBar menubar7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Statusbar statusbar3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ryuk.KashmirEditor
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.WindowAction = new global::Gtk.Action("WindowAction", global::Mono.Unix.Catalog.GetString("Window"), null, null);
			this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
			w1.Add(this.WindowAction, null);
			this.EncryptionAction = new global::Gtk.Action("EncryptionAction", global::Mono.Unix.Catalog.GetString("Encryption"), null, null);
			this.EncryptionAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Encryption");
			w1.Add(this.EncryptionAction, null);
			this.CesarAction = new global::Gtk.Action("CesarAction", global::Mono.Unix.Catalog.GetString("Cesar"), null, null);
			this.CesarAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cesar");
			w1.Add(this.CesarAction, null);
			this.DecryptAction = new global::Gtk.Action("DecryptAction", global::Mono.Unix.Catalog.GetString("Decrypt"), null, null);
			this.DecryptAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Decrypt");
			w1.Add(this.DecryptAction, null);
			this.CesarAction1 = new global::Gtk.Action("CesarAction1", global::Mono.Unix.Catalog.GetString("Cesar"), null, null);
			this.CesarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Cesar");
			w1.Add(this.CesarAction1, null);
			this.MD5Action = new global::Gtk.Action("MD5Action", global::Mono.Unix.Catalog.GetString("MD5"), null, null);
			this.MD5Action.ShortLabel = global::Mono.Unix.Catalog.GetString("MD5");
			w1.Add(this.MD5Action, null);
			this.MD5Action1 = new global::Gtk.Action("MD5Action1", global::Mono.Unix.Catalog.GetString("MD5"), null, null);
			this.MD5Action1.ShortLabel = global::Mono.Unix.Catalog.GetString("MD5");
			w1.Add(this.MD5Action1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ryuk.KashmirEditor";
			this.Title = global::Mono.Unix.Catalog.GetString("KashmirEditor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ryuk.KashmirEditor.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar7'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'/><menu name='WindowAction' action='WindowAction'/><menu name='EncryptionAction' action='EncryptionAction'><menuitem name='CesarAction' action='CesarAction'/><menuitem name='MD5Action' action='MD5Action'/></menu><menu name='DecryptAction' action='DecryptAction'><menuitem name='CesarAction1' action='CesarAction1'/><menuitem name='MD5Action1' action='MD5Action1'/></menu></menubar></ui>");
			this.menubar7 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar7")));
			this.menubar7.Name = "menubar7";
			this.vbox6.Add(this.menubar7);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.menubar7]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add(this.textview1);
			this.vbox6.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.statusbar3 = new global::Gtk.Statusbar();
			this.statusbar3.Name = "statusbar3";
			this.statusbar3.Spacing = 6;
			this.hbox4.Add(this.statusbar3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.statusbar3]));
			w5.Position = 0;
			this.vbox6.Add(this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 495;
			this.DefaultHeight = 300;
			this.Show();
			this.CesarAction.Activated += new global::System.EventHandler(this.encryptCesar);
			this.CesarAction1.Activated += new global::System.EventHandler(this.decryptCesar);
		}
	}
}
