
// This file has been generated by the GUI designer. Do not modify.
namespace ryuk
{
	public partial class FTPTerminal
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action WindowAction;

		private global::Gtk.Action SessionAction;

		private global::Gtk.Action SafeCloseAction;

		private global::Gtk.VBox vbox7;

		private global::Gtk.MenuBar menubar9;

		private global::Gtk.HBox hbox5;

		private global::Gtk.ScrolledWindow scrolledwindow3;

		private global::Gtk.VBox vbox9;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Statusbar statusbar5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ryuk.FTPTerminal
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
			w1.Add(this.EditAction, null);
			this.WindowAction = new global::Gtk.Action("WindowAction", global::Mono.Unix.Catalog.GetString("Window"), null, null);
			this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Window");
			w1.Add(this.WindowAction, null);
			this.SessionAction = new global::Gtk.Action("SessionAction", global::Mono.Unix.Catalog.GetString("Session"), null, null);
			this.SessionAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Session");
			w1.Add(this.SessionAction, null);
			this.SafeCloseAction = new global::Gtk.Action("SafeCloseAction", global::Mono.Unix.Catalog.GetString("Safe Close"), null, null);
			this.SafeCloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Safe Close");
			w1.Add(this.SafeCloseAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "ryuk.FTPTerminal";
			this.Title = global::Mono.Unix.Catalog.GetString("FTPTerminal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ryuk.FTPTerminal.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar9'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'/><menu name='WindowAction' action='WindowAction'/><menu name='SessionAction' action='SessionAction'><menuitem name='SafeCloseAction' action='SafeCloseAction'/></menu></menubar></ui>");
			this.menubar9 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar9")));
			this.menubar9.Name = "menubar9";
			this.vbox7.Add(this.menubar9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.menubar9]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Homogeneous = true;
			this.vbox9.Spacing = 6;
			w3.Add(this.vbox9);
			this.scrolledwindow3.Add(w3);
			this.hbox5.Add(this.scrolledwindow3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.scrolledwindow3]));
			w6.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w7 = new global::Gtk.Viewport();
			w7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Homogeneous = true;
			this.vbox8.Spacing = 6;
			w7.Add(this.vbox8);
			this.scrolledwindow1.Add(w7);
			this.hbox5.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.scrolledwindow1]));
			w10.Position = 1;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w11.Position = 1;
			// Container child vbox7.Gtk.Box+BoxChild
			this.statusbar5 = new global::Gtk.Statusbar();
			this.statusbar5.Name = "statusbar5";
			this.statusbar5.Spacing = 6;
			this.vbox7.Add(this.statusbar5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.statusbar5]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 494;
			this.Show();
		}
	}
}
